### ISSUE TITLE
Syncthing discovery : How can I get the ID of the host ?

### ISSUE THREAD

**Issue by bigbigbang** [firecat53/dockerfiles#13]
I'm running your docker image of syncthing_discovery. It works :) , and now I want to add this discovery server to syncthing instance. But for that I need the ID from host to add it like this : 
https://MYIP/v2/?id=IFQH6L5-SJGJKDU-47ZGXXK-LAK76BJ-4VSEN73-SDHGJDU-XXXXXXX-XXXXXXX

**Comment by firecat53** [comment]
Start the container from the directory container your cert and key files with a bash prompt:

    docker run -it -v $(pwd):/mnt --user root --entrypoint bash syncthing_discovery

Then run stdiscosrv once with the cert and pem arguments. It should print the server ID to stdout

    ./stdiscosrv -cert /mnt/cert.pem -key /mnt/key.pem
    Server device ID is 7DDRT7J-UICR4PM-PBIZYL3-MZOJ7X7-EX56JP6-IK6HHMW-S7EK32W-G3EUPQA

See the [documentation page](https://docs.syncthing.net/users/stdiscosrv.html)

**Comment by bigbigbang** [comment]
My bad, i'm new in my corporation, and they did something with graylog ^ wasn't working as I expected. It's okay now :)
Thanks
