### ISSUE TITLE
unclear docker create instruction in syncthing/README.md

### ISSUE THREAD

**Issue by code-surfer** [firecat53/dockerfiles#16]
The docker create command given in the `syncthing/README.md` does not work:
```
% docker create -v /config --name syncthing_config myscratch true
Unable to find image 'myscratch:latest' locally
Error response from daemon: pull access denied for myscratch, repository does not exist or may require 'docker login'
```
It is unclear to me what's supposed to look like...

Thanks!

**Comment by firecat53** [comment]
The README for this repository (dockerfiles) has the instructions for building the scratch (empty) container:

    FROM scratch
    LABEL "Maintainer"="<name> <email>"

Then:

    docker build -t myscratch .

Now you have the `myscratch` container to create your data-only container.

**Comment by code-surfer** [comment]
Thanks for the heads up!
I followed the link from https://docs.syncthing.net/users/contrib.html#packages-and-bundlings to https://github.com/firecat53/dockerfiles/tree/master/syncthing. It presents the `README.md` in a directory with three files and looks self-contained because there's little indication that one has to look further up...
