### ISSUE TITLE
syncthing setup instruction does not work with docker 

### ISSUE THREAD

**Issue by code-surfer** [firecat53/dockerfiles#17]
The command `docker run --rm --volumes-from syncthing_config --user root syncthing chown -R syncthing:users /config` given in the README does not work. It only makes the syncthing command show its usage. According to the `docker-run` man page, the ENTRYPOINT is purposely more difficult to override. When I add a `--entrypoint=` option, it works.
```
% docker run --rm --volumes-from syncthing_config --user root --entrypoint= syncthing chown -R syncthing:users /config
% docker --version
Docker version 18.06.1-ce, build e68fc7a
```

The remainder of the instructions work, my dockerized syncthing is syncing fine with my other peers.

**Comment by firecat53** [comment]
Ah, good catch. I'll go through and make sure I get that fixed for all the relevant Dockerfiles. Correct line should be:

    docker run --rm --volumes-from syncthing_config --user root --entrypoint "/bin/sh" syncthing -c "chown -R syncthing:users /config"

**Comment by firecat53** [comment]
Fixed with d6098d
