### ISSUE TITLE
Issues running openvpn-client-pia

### ISSUE THREAD

**Issue by sleepysloth17** [firecat53/dockerfiles#19]
@firecat53 Apologies in advance, I'm not particularly knowledgable about docker, but figured setting up a dockerised home server would be a good way to learn, and came across your pretty thorough repo.

I'm having trouble trying to use your openvpn-client-pia docker container.
In the build/configure stage of your readme, the image builds fine amd the pia_port volume works. (I didn't create the volume for the pia_config as figured I'd just bind-mount the config into the container as you said).

To run the container, I use: `docker run -d --cap-add=NET_ADMIN -e LOCAL_NETWORKS=192.168.0.0/24 -v  /"$(pwd)":/config -v pia_port:/var/run/pia/ -p 2222:22 -p 9091:9091 --name=openvpn_run openvpn-client`, which I run from within my file containing the config.

(I removed the --device argument as that caused an `Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "C": no such file or directory.`.)

However, the container immediately stops, and when running `docker logs openvpn_run` I have the error `In [CMD-LINE]:1: Error opening configuration file: /config/pia.ovpn` which suggests to me I'm doing something wrong with the volume?

Any help would be appreciated, and thanks in advance!

**Comment by firecat53** [comment]
First thing is to drop the leading `/` on the pwd command. Should just look like `-v "$(pwd)":/config`

You should probably also investigate the other error. It won't work without /dev/net/tun. That should exist on your Docker host. Do you have the tun module loaded? `lsmod|grep tun` What platform are you running Docker on?

**Comment by sleepysloth17** [comment]
The leading `/` is to get around a problem with using docker mount with git bash, else it inserts `;C` at the end of the path. Yeah that makes sense, I'm running it on a windows 10 desktop machine whilst trying to get it to work, should I instead be using linux? Thanks for the response!

**Comment by firecat53** [comment]
Nice work troubleshooting! I have no Windows machines to try it on so I'm glad it worked with a Linux host.
Not sure why you would need to alter /etc/resolv.conf. Mine just has the nameserver IP addresses for PIA.
If you are still forwarding port 9091 but using a Deluge client, that would be your problem. 9091 is the transmission port. Deluge uses 8112.

**Comment by firecat53** [comment]
@sleepysloth17, did you ever get this resolved and working?

**Comment by firecat53** [comment]
Closing...please reopen if you need more help! Thanks for your interest.
